/**
 * 100 unique spirit-boosting one-liners for team leaders.
 * Randomly picked for each WhatsApp message.
 */
export const SPIRIT_LINES = [
    "Show them what legends are made of! 🔥",
    "The battleground is yours — own it! 💥",
    "Play like there's no tomorrow! ⚡",
    "Your squad is built different. Prove it! 🏆",
    "Champions don't wait — they dominate! 👑",
    "Every bullet counts. Make them all matter! 🎯",
    "Fear nothing. Conquer everything! 💪",
    "This is YOUR moment. Seize it! 🌟",
    "Legends aren't born — they're made in battle! ⚔️",
    "Go out there and write history! 📜",
    "The zone is closing. Time to shine! ✨",
    "Trust your team, trust your aim! 🎮",
    "Play smart, play hard, play to win! 🧠",
    "Your enemies should fear your name! 😤",
    "Victory favors the bold! 🦁",
    "One team, one dream, one chicken dinner! 🍗",
    "Drop hot, fight hard, survive! 🪂",
    "No mercy. No excuses. Just victory! 🏅",
    "The final circle belongs to YOU! 🎯",
    "Rise up and make your mark! 🚀",
    "Play with heart, win with pride! ❤️",
    "Your grind brought you here. Now finish it! 💎",
    "Be the storm they never saw coming! 🌪️",
    "Clutch it like you always do! 🔒",
    "Today you fight. Tomorrow you celebrate! 🎉",
    "The lobby should tremble when you enter! 😈",
    "Trust the process. Execute the plan! 📋",
    "Your team chemistry is unmatched! 🤝",
    "Go get that chicken dinner! 🍗🏆",
    "Aim high, shoot higher! 🎯",
    "The grind never stops. Neither do you! 💪",
    "Make every round count! 🔫",
    "Silence the doubters with your gameplay! 🤫",
    "You've trained for this. Now deliver! 🎖️",
    "Be the last squad standing! 🏔️",
    "Play fearless. Win gracious! 🙏",
    "Your squad's synergy is fire! 🔥",
    "Let your skills do the talking! 💬",
    "This tournament is yours for the taking! 🏆",
    "Stay focused, stay lethal! 🎯",
    "Pressure makes diamonds. Shine bright! 💎",
    "Born to compete, built to win! 🛡️",
    "The battlefield respects no one — earn it! ⚔️",
    "Your enemies are your stepping stones! 🪨",
    "Play like a predator, think like a genius! 🧠",
    "Squad goals: chicken dinner! 🍗",
    "Leave nothing on the battlefield! 💥",
    "Your name will echo in the kill feed! 📢",
    "Trust your reflexes, they won't fail you! ⚡",
    "The leaderboard is calling your name! 📊",
    "Every match is a chance to be legendary! 🌟",
    "Rotate smart, fight smarter! 🗺️",
    "Your teamwork is your superpower! 🦸",
    "Dominate the zone like you own it! 👑",
    "Keep calm and get the dinner! 😎",
    "Hustle hits different when it's tournament day! 🔥",
    "You're not just playing — you're conquering! ⚔️",
    "The circle favors the brave! 🎯",
    "Make this the match they'll talk about! 🗣️",
    "Your dedication is about to pay off! 💰",
    "Fight together, win together! 🤜🤛",
    "No retreat, no surrender! 🛡️",
    "The arena is set. Time to dominate! 🏟️",
    "Your journey to the top starts NOW! 🚀",
    "Play with fire, but don't get burned! 🔥",
    "Every knockdown is one step closer to victory! 📈",
    "The squad that vibes together, wins together! 🎵",
    "Channel your inner warrior! ⚔️",
    "This is what you've been waiting for! ⏰",
    "Stay hungry, stay dangerous! 🐺",
    "Make them remember your team name! 💀",
    "Precision over panic. Always! 🎯",
    "Your best game is yet to come! 🌅",
    "Fight like you mean it! 💪",
    "The crown is waiting for you! 👑",
    "Time to turn practice into performance! 🎭",
    "Your squad is the real deal! 💯",
    "Believe in your aim, believe in your team! 🙌",
    "Greatness is one match away! 🏅",
    "Play to inspire, win to celebrate! 🎊",
    "Your enemies don't know what's coming! 😏",
    "Today's MVP? That's YOU! 🌟",
    "The chicken dinner has your name on it! 🍗",
    "Drop, loot, dominate, repeat! 🔄",
    "Stay sharp, stay deadly! 🗡️",
    "Your squad's energy is unmatched! ⚡",
    "Write your own victory story! 📖",
    "The zone is your playground! 🎢",
    "No tilt, just domination! 😤",
    "Your crosshair is destiny! 🎯",
    "Bring the thunder! ⛈️",
    "You didn't come this far to only come this far! 🏃",
    "The grind was worth it. Now prove it! 💎",
    "Squad up and show up! 🤝",
    "This is your battlefield. Own every inch! 🗺️",
    "Calculated plays, devastating results! 🧮",
    "Your comeback story starts today! 🔄",
    "Go hard or go home. Choose wisely! 🏠",
    "Let's gooo! Time to feast! 🍽️",
    "The victory royale is destiny! ✨",
];

/**
 * Get a random spirit line. Optionally pass an index for deterministic selection.
 */
export function getRandomSpiritLine(index?: number): string {
    if (index !== undefined) {
        return SPIRIT_LINES[index % SPIRIT_LINES.length];
    }
    return SPIRIT_LINES[Math.floor(Math.random() * SPIRIT_LINES.length)];
}
