/**
 * 100 real motivational one-liners for team leaders.
 * Popular quotes + universal inspiration. Randomly picked per message.
 */
export const SPIRIT_LINES = [
    "Believe you can and you're halfway there. 💪",
    "The only way to do great work is to love what you do. ✨",
    "It does not matter how slowly you go as long as you do not stop. 🚀",
    "Success is not final, failure is not fatal — it is the courage to continue that counts. 🔥",
    "Hard work beats talent when talent doesn't work hard. 💯",
    "Dream big. Start small. Act now. ⚡",
    "The harder you work, the luckier you get. 🍀",
    "Don't watch the clock; do what it does — keep going. ⏰",
    "Champions keep playing until they get it right. 🏆",
    "Your limitation is only your imagination. 🌟",
    "Push yourself, because no one else is going to do it for you. 💪",
    "Great things never come from comfort zones. 🔥",
    "The best time to start was yesterday. The next best time is now. ⏳",
    "Don't stop when you're tired. Stop when you're done. ✅",
    "Wake up with determination. Go to bed with satisfaction. 🌅",
    "Little things make big days. ☀️",
    "It's going to be hard, but hard does not mean impossible. 💎",
    "Don't wait for opportunity. Create it. 🛠️",
    "The secret of getting ahead is getting started. 🚀",
    "Stay focused and never give up. 🎯",
    "Hustle in silence. Let success make the noise. 🤫",
    "Good things come to those who hustle. 💪",
    "Doubt kills more dreams than failure ever will. 🌟",
    "Work hard in silence, let your success be your noise. 🔥",
    "The man who moves a mountain begins by carrying away small stones. 🏔️",
    "Strength does not come from winning. Your struggles develop your strength. 💪",
    "Be so good they can't ignore you. ✨",
    "Everything you've ever wanted is on the other side of fear. 🦁",
    "Fall seven times, stand up eight. 🔄",
    "Winners never quit, and quitters never win. 🏆",
    "Tough times never last, but tough people do. 💎",
    "It always seems impossible until it's done. ✅",
    "Don't count the days, make the days count. 📅",
    "A winner is a dreamer who never gives up. 🌟",
    "You miss 100% of the shots you don't take. 🎯",
    "The comeback is always stronger than the setback. 🔥",
    "Believe in yourself and all that you are. 💫",
    "Success is walking from failure to failure with no loss of enthusiasm. 🚶",
    "The only impossible journey is the one you never begin. 🗺️",
    "Strive for progress, not perfection. 📈",
    "Your only limit is you. ♾️",
    "Don't be afraid to give up the good to go for the great. 🌟",
    "Today's pain is tomorrow's power. 💪",
    "Action is the foundational key to all success. 🔑",
    "What you do today can improve all your tomorrows. 🌅",
    "Be stronger than your excuses. 🛡️",
    "You are braver than you believe, stronger than you seem, and smarter than you think. 🧠",
    "If it doesn't challenge you, it doesn't change you. 🔥",
    "Success doesn't just find you. You have to go out and get it. 🏃",
    "The future belongs to those who believe in the beauty of their dreams. ✨",
    "Every champion was once a contender that refused to give up. 🏅",
    "Do something today that your future self will thank you for. 🙏",
    "Stay hungry. Stay foolish. 🍎",
    "You don't have to be great to start, but you have to start to be great. 🚀",
    "Small steps every day lead to big results. 👣",
    "Discipline is the bridge between goals and accomplishment. 🌉",
    "The pain you feel today will be the strength you feel tomorrow. 💪",
    "Your attitude determines your direction. 🧭",
    "Winning is not everything, but wanting to win is. 🔥",
    "In the middle of every difficulty lies opportunity. 💡",
    "Nothing worth having comes easy. 💎",
    "Set your goals high, and don't stop till you get there. 🎯",
    "Go the extra mile. It's never crowded. 🛤️",
    "When you feel like quitting, think about why you started. 💭",
    "If you can dream it, you can do it. ✨",
    "Make each day your masterpiece. 🎨",
    "You were born to win, but to be a winner you must plan to win and prepare to win. 🏆",
    "One day or day one. You decide. 📌",
    "Don't limit your challenges. Challenge your limits. ♾️",
    "The only person you should try to be better than is who you were yesterday. 📈",
    "Risk more than others think is safe. Dream more than others think is practical. 🌈",
    "Excuses don't build empires. 🏗️",
    "Prove them wrong. 😤",
    "You are one decision away from a totally different life. 🔑",
    "Life begins at the end of your comfort zone. 🌍",
    "Be fearless in the pursuit of what sets your soul on fire. 🔥",
    "Stop wishing. Start doing. ✅",
    "Impossible is just an opinion. 💯",
    "Make it happen. Shock everyone. ⚡",
    "Sometimes later becomes never. Do it now. ⏰",
    "Don't decrease the goal. Increase the effort. 📈",
    "The only bad workout is the one that didn't happen. 💪",
    "Stay positive, work hard, make it happen. ☀️",
    "Success is the sum of small efforts repeated day in and day out. 🔄",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. 🧠",
    "Stars can't shine without darkness. 🌟",
    "Turn your wounds into wisdom. 📖",
    "You are enough just as you are. 💫",
    "Keep going. Everything you need will come to you at the perfect time. ⏳",
    "The difference between ordinary and extraordinary is that little extra. ✨",
    "Opportunities don't happen. You create them. 🛠️",
    "The best revenge is massive success. 🔥",
    "Enjoy the journey, not just the destination. 🗺️",
    "Be the energy you want to attract. ⚡",
    "Don't tell people your plans. Show them your results. 📊",
    "Luck is what happens when preparation meets opportunity. 🍀",
    "Rise above the storm and you will find the sunshine. ☀️",
    "Stay patient and trust your journey. 🛤️",
    "The grind includes days you don't feel like grinding. 💪",
    "If not now, when? If not you, who? 🔥",
];

/**
 * Get a random spirit line. Optionally pass an index for deterministic selection.
 */
export function getRandomSpiritLine(index?: number): string {
    if (index !== undefined) {
        return SPIRIT_LINES[index % SPIRIT_LINES.length];
    }
    return SPIRIT_LINES[Math.floor(Math.random() * SPIRIT_LINES.length)];
}
